spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gymfactory
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true