INSERT INTO exercises (name, description, muscle_group, category, created_at)
VALUES
-- Abdominais
('Abdominal Canivete', 'Movimento simultâneo de flexão do tronco e elevação das pernas, aproximando mãos e pés.', 'ABDOMEN', 'MUSCULACAO', NOW()),
('Abdominal com Rodinha', 'Deslizamento frontal com roda abdominal, exigindo forte contração do core na extensão e retorno.', 'ABDOMEN', 'MUSCULACAO', NOW()),
('Abdominal Crunches', 'Flexão curta do tronco no solo, focando na ativação da parte superior do abdômen.', 'ABDOMEN', 'MUSCULACAO', NOW()),
('Abdominal Dead Bug', 'Deitado de costas, movimentação alternada e controlada de braços e pernas opostas.', 'ABDOMEN', 'MUSCULACAO', NOW()),
('Abdominal Escalador', 'Em posição de prancha, puxada alternada e rápida dos joelhos em direção ao peito.', 'ABDOMEN', 'MUSCULACAO', NOW()),
('Abdominal Infra', 'Elevação das pernas a partir da posição deitada, focando na região inferior do abdômen.', 'ABDOMEN', 'MUSCULACAO', NOW()),
('Abdominal Oblíquo', 'Flexão do tronco com rotação, direcionando o ombro ou cotovelo ao joelho oposto.', 'ABDOMEN', 'MUSCULACAO', NOW()),
('Abdominal Prancha', 'Sustentação isométrica do corpo alinhado, apoiado nos antebraços e pontas dos pés.', 'ABDOMEN', 'MUSCULACAO', NOW()),
('Abdominal Remador', 'Flexão completa do tronco abraçando os joelhos no final do movimento.', 'ABDOMEN', 'MUSCULACAO', NOW()),
('Abdominal Supra', 'Elevação clássica do tronco com os joelhos flexionados e pés fixos no chão.', 'ABDOMEN', 'MUSCULACAO', NOW()),
('Perdigueiro', 'Extensão alternada de braço e perna opostos na posição de quatro apoios, focando em estabilidade.', 'ABDOMEN', 'MUSCULACAO', NOW()),

-- Inferiores
('Abdução de Quadril', 'Afastamento lateral das pernas, ativando principalmente os glúteos e abdutores.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Adução de Quadril', 'Fechamento das pernas contra resistência, focando na parte interna das coxas.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Afundo', 'Passada à frente com flexão dos dois joelhos a 90 graus, mantendo o tronco ereto.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Agachamento Búlgaro', 'Agachamento unilateral com a perna de trás apoiada em um banco ou superfície elevada.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Agachamento com Halteres', 'Flexão e extensão dos joelhos e quadril segurando halteres ao lado do corpo.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Agachamento com Salto', 'Agachamento seguido de um salto vertical explosivo, focando em potência.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Agachamento Frontal', 'Agachamento realizado com a barra apoiada na parte frontal dos ombros.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Agachamento Hack', 'Agachamento realizado em máquina guiada com apoio para as costas.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Agachamento Isométrico', 'Sustentação estática na posição de agachamento, geralmente encostado em uma parede.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Agachamento Livre', 'Agachamento tradicional com barra livre nas costas, movimento base para membros inferiores.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Agachamento Sumô', 'Agachamento com as pernas mais afastadas e pontas dos pés direcionadas para fora.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Avanço', 'Passadas sucessivas à frente flexionando os joelhos, caminhando pelo espaço.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Cadeira Extensora', 'Extensão dos joelhos em máquina sentada, isolando a musculatura do quadríceps.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Cadeira Flexora', 'Flexão dos joelhos em máquina sentada, isolando a musculatura isquiotibial.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Elevação de Quadril', 'Elevação da pelve a partir da posição deitada com os joelhos flexionados e pés no chão.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Flexão Nórdica', 'Exercício avançado de peso corporal para isquiotibiais, descendo o tronco com joelhos fixos no chão.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Glúteos 4 Apoios', 'Extensão de quadril com perna flexionada na posição de quatro apoios.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Glúteos Coice na Polia', 'Extensão de quadril unilateral em pé utilizando cabo/polia baixa.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Leg Press 45', 'Empurrada de carga com as pernas em máquina inclinada a 45 graus.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Leg Press 90', 'Empurrada de carga direcionada para o alto na posição deitada de costas.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Leg Press Horizontal', 'Empurrada de carga com as pernas na posição sentada, paralela ao solo.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Levantamento Terra', 'Elevação da barra do chão até a extensão completa do quadril e tronco.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Levantamento Terra Sumô', 'Levantamento terra com base bem afastada e pegada fechada por dentro das pernas.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Mesa Flexora', 'Flexão de joelhos na posição deitada de bruços, ativando a parte posterior da coxa.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Panturrilha Hack', 'Elevação nas pontas dos pés utilizando o peso da máquina de agachamento hack.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Panturrilha no Leg Press', 'Extensão dos tornozelos empurrando a plataforma do leg press apenas com as pontas dos pés.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Panturrilha no Smith', 'Elevação de panturrilha em pé utilizando a barra guiada da máquina Smith.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Panturrilha Sentado', 'Elevação de calcanhares em máquina sentada, focando no músculo sóleo.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Passada', 'Semelhante ao avanço, execução de afundos contínuos em deslocamento.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Pistol', 'Agachamento unilateral profundo sustentando o peso do corpo e mantendo a outra perna reta.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Stiff', 'Flexão de tronco com joelhos semi-estendidos e barra, focando na cadeia posterior.', 'INFERIORES', 'MUSCULACAO', NOW()),
('Subida no Caixote', 'Passo elevado (step-up) unilateral pisando sobre uma caixa resistente ou banco.', 'INFERIORES', 'MUSCULACAO', NOW()),

-- Aeróbio
('Air Bike', 'Bicicleta ergométrica que utiliza a resistência do ar, movimentando braços e pernas simultaneamente.', 'AEROBIO', 'AEROBICO', NOW()),
('Bicicleta', 'Exercício cardiovascular simulando pedalada em equipamento ergométrico.', 'AEROBIO', 'AEROBICO', NOW()),
('Elíptico', 'Máquina cardiovascular que simula a caminhada ou corrida sem impacto nas articulações.', 'AEROBIO', 'AEROBICO', NOW()),
('Escada Máquina', 'Simulador de subida contínua de degraus para treino cardiovascular intenso.', 'AEROBIO', 'AEROBICO', NOW()),
('Esteira', 'Caminhada ou corrida contínua em lona rolante automatizada.', 'AEROBIO', 'AEROBICO', NOW()),
('Polichinelo', 'Salto coordenado afastando e aproximando braços e pernas repetidamente.', 'AEROBIO', 'AEROBICO', NOW()),
('Pular Corda', 'Salto rítmico por cima de uma corda em movimento, excelente para condicionamento.', 'AEROBIO', 'AEROBICO', NOW()),
('Remo', 'Simulação mecânica do movimento de remar, trabalhando cardio e múltiplos grupos musculares.', 'AEROBIO', 'AEROBICO', NOW()),

-- Alongamento
('Alongamento de Abdômen', 'Extensão da coluna no solo apoiando as mãos, similar à postura da cobra na Yoga.', 'ALONGAMENTO', 'ALONGAMENTO', NOW()),
('Alongamento de Adutores', 'Abertura das pernas para alongar a parte interna das coxas, como a posição de borboleta.', 'ALONGAMENTO', 'ALONGAMENTO', NOW()),
('Alongamento de Antebraço', 'Extensão e flexão do punho auxiliado pela outra mão para soltar a musculatura do antebraço.', 'ALONGAMENTO', 'ALONGAMENTO', NOW()),
('Alongamento de Coluna', 'Flexões e torções suaves do tronco para aliviar tensões e melhorar a flexibilidade vertebral.', 'ALONGAMENTO', 'ALONGAMENTO', NOW()),
('Alongamento de Dorsal', 'Movimentos para esticar os músculos das costas, como pendurar-se em uma barra ou abraçar uma pilastra.', 'ALONGAMENTO', 'ALONGAMENTO', NOW()),
('Alongamento de Glúteos', 'Puxada da perna flexionada contra o peito ou posições cruzadas para alongar a região glútea.', 'ALONGAMENTO', 'ALONGAMENTO', NOW()),
('Alongamento de Ombros', 'Cruzar um braço à frente do peito pressionando-o, ou realizar rotações e extensões articulares.', 'ALONGAMENTO', 'ALONGAMENTO', NOW()),
('Alongamento de Panturrilha', 'Apoio na parede inclinando o corpo à frente mantendo o calcanhar da perna de trás fixo no chão.', 'ALONGAMENTO', 'ALONGAMENTO', NOW()),
('Alongamento de Peitoral', 'Apoio do antebraço na parede e giro do tronco para expandir e alongar a caixa torácica.', 'ALONGAMENTO', 'ALONGAMENTO', NOW()),
('Alongamento de Pescoço', 'Inclinações, flexões e rotações suaves da cabeça para liberar tensões da região cervical.', 'ALONGAMENTO', 'ALONGAMENTO', NOW()),
('Alongamento de Posteriores', 'Flexão do tronco à frente tentando alcançar os pés com as pernas estendidas.', 'ALONGAMENTO', 'ALONGAMENTO', NOW()),
('Alongamento de Punho', 'Rotações circulares e extensões manuais para soltar as articulações dos punhos.', 'ALONGAMENTO', 'ALONGAMENTO', NOW()),
('Alongamento de Quadríceps', 'Em pé, puxar o pé por trás em direção ao glúteo mantendo o joelho apontado para baixo.', 'ALONGAMENTO', 'ALONGAMENTO', NOW()),
('Alongamento de Tríceps', 'Dobrar o braço atrás da cabeça e empurrar o cotovelo levemente para trás e para baixo.', 'ALONGAMENTO', 'ALONGAMENTO', NOW()),

-- Dorsal
('Banco Lombar', 'Extensão do tronco no banco romano, focando na musculatura da região lombar.', 'DORSAL', 'MUSCULACAO', NOW()),
('Barra Fixa', 'Puxada vertical do corpo usando o peso próprio pendurado em uma barra.', 'DORSAL', 'MUSCULACAO', NOW()),
('Barra Fixa Gráviton', 'Puxada vertical em máquina que oferece plataforma de assistência, facilitando o movimento da barra fixa.', 'DORSAL', 'MUSCULACAO', NOW()),
('Crucifixo Inverso', 'Abertura dos braços para trás (abdução horizontal), focando no deltoide posterior e romboides.', 'DORSAL', 'MUSCULACAO', NOW()),
('Face Pull', 'Puxada de cabo na altura do rosto, ativando a parte superior das costas e manguito rotador.', 'DORSAL', 'MUSCULACAO', NOW()),
('Pulldown', 'Extensão de ombros com braços esticados puxando a barra da polia alta para baixo, isolando o latíssimo do dorso.', 'DORSAL', 'MUSCULACAO', NOW()),
('Pullover', 'Movimento de arco passando o halter por trás da cabeça deitado no banco, expandindo a caixa torácica e ativando dorsais.', 'DORSAL', 'MUSCULACAO', NOW()),
('Puxada Aberta', 'Puxada vertical na polia alta com pegada bem afastada para focar na largura das costas.', 'DORSAL', 'MUSCULACAO', NOW()),
('Puxada Fechada', 'Puxada vertical na polia alta utilizando um puxador triângulo ou pegada supinada estreita.', 'DORSAL', 'MUSCULACAO', NOW()),
('Remada Baixa', 'Puxada horizontal na máquina de cabos com o corpo na posição sentada.', 'DORSAL', 'MUSCULACAO', NOW()),
('Remada Cavalinho', 'Remada com o tronco inclinado utilizando uma barra presa articulada no chão (T-bar row).', 'DORSAL', 'MUSCULACAO', NOW()),
('Remada Curvada', 'Puxada de barra livre em direção ao abdômen mantendo o tronco inclinado à frente.', 'DORSAL', 'MUSCULACAO', NOW()),
('Remada Máquina', 'Puxada horizontal em máquina articulada, geralmente com apoio acolchoado para o peito.', 'DORSAL', 'MUSCULACAO', NOW()),
('Remada Unilateral (Serrote)', 'Remada com halter executada um braço de cada vez, apoiando a outra mão e joelho no banco.', 'DORSAL', 'MUSCULACAO', NOW()),

-- Funcional
('Burpee', 'Sequência rápida combinando agachamento, flexão de braços, retorno ao agachamento e salto vertical.', 'FUNCIONAL', 'FUNCIONAL', NOW()),
('Corda Naval', 'Movimentação ondulatória de cordas pesadas para trabalhar força de membros superiores, potência e sistema cardiovascular.', 'FUNCIONAL', 'FUNCIONAL', NOW()),
('Deslocamento Lateral', 'Movimentação rápida de passos de um lado para o outro mantendo o centro de gravidade baixo.', 'FUNCIONAL', 'FUNCIONAL', NOW()),
('Escada de Agilidade', 'Exercícios coordenados de movimentação rápida dos pés dentro dos espaços de uma escada fixada no chão.', 'FUNCIONAL', 'FUNCIONAL', NOW()),
('Skipping', 'Corrida estacionária em ritmo intenso com elevação alta e alternada dos joelhos.', 'FUNCIONAL', 'FUNCIONAL', NOW()),
('Swing Kettlebell', 'Movimento balístico explosivo de quadril impulsionando o peso do kettlebell à frente.', 'FUNCIONAL', 'FUNCIONAL', NOW()),

-- Ombro
('Desenvolvimento Arnold', 'Empurrada vertical com halteres, iniciando com palmas para o rosto e rotacionando os punhos durante a subida.', 'OMBRO', 'MUSCULACAO', NOW()),
('Desenvolvimento com Barra', 'Empurrada vertical clássica da barra a partir da linha frontal dos ombros ou clavícula.', 'OMBRO', 'MUSCULACAO', NOW()),
('Desenvolvimento com Halteres', 'Empurrada vertical livre, simultânea ou alternada, usando halteres na linha dos ombros.', 'OMBRO', 'MUSCULACAO', NOW()),
('Desenvolvimento Máquina', 'Empurrada vertical utilizando máquina guiada ou articulada para isolar os deltoides.', 'OMBRO', 'MUSCULACAO', NOW()),
('Elevação Frontal', 'Levantamento de pesos mantendo os braços estendidos ou semiflexionados à frente do corpo.', 'OMBRO', 'MUSCULACAO', NOW()),
('Elevação Lateral', 'Levantamento de pesos abrindo os braços lateralmente até a linha dos ombros.', 'OMBRO', 'MUSCULACAO', NOW()),
('Encolhimento de Ombros', 'Movimento de elevação das escápulas em direção às orelhas para focar no músculo trapézio.', 'OMBRO', 'MUSCULACAO', NOW()),
('Remada Alta', 'Puxada vertical de barra, halteres ou polia rente ao corpo até a linha do peito ou queixo.', 'OMBRO', 'MUSCULACAO', NOW()),

-- Peitoral
('Crucifixo', 'Abertura e fechamento em arco dos braços com halteres, executado deitado em banco reto.', 'PEITORAL', 'MUSCULACAO', NOW()),
('Crucifixo Inclinado', 'Abertura e fechamento em arco dos braços com halteres, executado em banco com inclinação positiva.', 'PEITORAL', 'MUSCULACAO', NOW()),
('Flexão de Braços', 'Empurrada do peso do próprio corpo contra o solo a partir de uma posição de prancha.', 'PEITORAL', 'MUSCULACAO', NOW()),
('Manguito Rotador Externo', 'Rotação do ombro para fora contra resistência de elástico ou polia para fortalecer estabilizadores articulares.', 'PEITORAL', 'MUSCULACAO', NOW()),
('Manguito Rotador Interno', 'Rotação do ombro para dentro contra resistência de elástico ou polia para fortalecer estabilizadores articulares.', 'PEITORAL', 'MUSCULACAO', NOW()),
('Peck Deck', 'Fechamento dos braços (adução horizontal) em máquina voador, isolando fortemente a musculatura do peitoral.', 'PEITORAL', 'MUSCULACAO', NOW()),
('Supino Declinado', 'Exercício de empurrada executado em banco com inclinação negativa, focando na porção inferior do peitoral.', 'PEITORAL', 'MUSCULACAO', NOW()),
('Supino Inclinado', 'Exercício de empurrada executado em banco com inclinação positiva, focando na porção superior (clavicular) do peitoral.', 'PEITORAL', 'MUSCULACAO', NOW()),
('Supino Máquina', 'Empurrada horizontal segura em equipamento guiado ou articulado sentado.', 'PEITORAL', 'MUSCULACAO', NOW()),
('Supino Reto', 'Exercício clássico de empurrada deitado no banco horizontal, utilizando barra ou halteres.', 'PEITORAL', 'MUSCULACAO', NOW()),

-- Bíceps
('Rosca Alternada', 'Flexão de cotovelos com halteres, levantando um braço de cada vez com supinação no movimento.', 'BICEPS', 'MUSCULACAO', NOW()),
('Rosca Concentrada', 'Flexão de cotovelo unilateral com a parte posterior do braço estabilizada na parte interna da coxa.', 'BICEPS', 'MUSCULACAO', NOW()),
('Rosca Direta', 'Flexão de cotovelos clássica executada com barra reta ou W de forma simultânea.', 'BICEPS', 'MUSCULACAO', NOW()),
('Rosca Martelo', 'Flexão de cotovelos mantendo a pegada neutra (palmas voltadas para o corpo), ativando bíceps e braquiorradial.', 'BICEPS', 'MUSCULACAO', NOW()),
('Rosca Scott', 'Flexão de cotovelos apoiando os braços na prancha inclinada (banco Scott) para isolamento máximo e evitar impulsos.', 'BICEPS', 'MUSCULACAO', NOW()),

-- Antebraço
('Rosca de Punho', 'Flexão dos punhos segurando uma barra ou halteres com as palmas voltadas para cima, isolando flexores do antebraço.', 'ANTEBRACO', 'MUSCULACAO', NOW()),
('Rosca Inversa', 'Flexão de cotovelos utilizando pegada pronada (palmas para baixo), focando nos extensores do antebraço e braquial.', 'ANTEBRACO', 'MUSCULACAO', NOW()),

-- Tríceps
('Tríceps Banco', 'Extensão dos cotovelos sustentando o corpo com as mãos apoiadas em um banco ou superfície logo atrás das costas.', 'TRICEPS', 'MUSCULACAO', NOW()),
('Tríceps Coice', 'Extensão isolada do cotovelo para trás mantendo o braço paralelo ao tronco inclinado.', 'TRICEPS', 'MUSCULACAO', NOW()),
('Tríceps Francês', 'Extensão de cotovelos segurando o peso por trás e por cima da cabeça, alongando bem a porção longa do tríceps.', 'TRICEPS', 'MUSCULACAO', NOW()),
('Tríceps na Polia', 'Extensão de cotovelos puxando o cabo da polia alta de cima para baixo (com barra, corda ou triângulo).', 'TRICEPS', 'MUSCULACAO', NOW()),
('Tríceps Paralelas', 'Levantamento do próprio peso corporal empurrando barras paralelas para baixo, ativando tríceps e peitoral.', 'TRICEPS', 'MUSCULACAO', NOW()),
('Tríceps Supinado', 'Supino reto realizado com uma pegada fechada (na largura dos ombros ou menor), transferindo a ênfase para os tríceps.', 'TRICEPS', 'MUSCULACAO', NOW()),
('Tríceps Testa', 'Flexão e extensão de cotovelos deitado em banco, descendo a barra ou halteres em direção à testa ou atrás da cabeça.', 'TRICEPS', 'MUSCULACAO', NOW()),

-- Mobilidade
('Mobilidade de Cervical', 'Movimentos controlados e dinâmicos para melhorar a amplitude articular e diminuir a tensão no pescoço.', 'MOBILIDADE', 'MOBILIDADE', NOW()),
('Mobilidade de Corpo Inteiro', 'Rotina dinâmica conectando várias articulações do corpo em movimentos fluídos e contínuos.', 'MOBILIDADE', 'MOBILIDADE', NOW()),
('Mobilidade de Escápula', 'Movimentos de retração, protração, elevação e depressão das omoplatas para melhorar o controle e saúde das costas.', 'MOBILIDADE', 'MOBILIDADE', NOW()),
('Mobilidade de Ombro', 'Rotações articulares, passagens de bastão e exercícios dinâmicos para abrir o ângulo de articulação dos ombros.', 'MOBILIDADE', 'MOBILIDADE', NOW()),
('Mobilidade de Quadril', 'Exercícios de rotação e abertura pélvica, como as posições 90/90 ou cócoras profundas, para destravar o quadril.', 'MOBILIDADE', 'MOBILIDADE', NOW()),
('Mobilidade de Tornozelo', 'Movimentos de dorsiflexão, trabalhando amplitude contra uma parede, para melhorar o agachamento e pisada.', 'MOBILIDADE', 'MOBILIDADE', NOW()),
('Mobilidade Dorsal', 'Exercícios focados em destravar e criar maior extensão e rotação na parte média e superior das costas.', 'MOBILIDADE', 'MOBILIDADE', NOW()),
('Mobilidade Torácica', 'Rotações dinâmicas e extensões visando destravar a caixa torácica, auxiliando muito na respiração e postura correta.', 'MOBILIDADE', 'MOBILIDADE', NOW());