INSERT INTO exercises (name, muscle_group, category, active, created_at)
VALUES
-- Abdominais
('Abdominal Canivete', 'ABDOMEN', 'MUSCULACAO', true, NOW()),
('Abdominal com Rodinha', 'ABDOMEN', 'MUSCULACAO', true, NOW()),
('Abdominal Crunches', 'ABDOMEN', 'MUSCULACAO', true, NOW()),
('Abdominal Dead Bug', 'ABDOMEN', 'MUSCULACAO', true, NOW()),
('Abdominal Escalador', 'ABDOMEN', 'MUSCULACAO', true, NOW()),
('Abdominal Infra', 'ABDOMEN', 'MUSCULACAO', true, NOW()),
('Abdominal Oblíquo', 'ABDOMEN', 'MUSCULACAO', true, NOW()),
('Abdominal Prancha', 'ABDOMEN', 'MUSCULACAO', true, NOW()),
('Abdominal Remador', 'ABDOMEN', 'MUSCULACAO', true, NOW()),
('Abdominal Supra', 'ABDOMEN', 'MUSCULACAO', true, NOW()),
('Perdigueiro', 'ABDOMEN', 'MUSCULACAO', true, NOW()),

-- Inferiores
('Abdução de Quadril', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Adução de Quadril', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Afundo', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Agachamento Búlgaro', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Agachamento com Halteres', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Agachamento com Salto', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Agachamento Frontal', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Agachamento Hack', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Agachamento Isométrico', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Agachamento Livre', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Agachamento Sumô', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Avanço', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Cadeira Extensora', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Cadeira Flexora', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Elevação de Quadril', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Flexão Nórdica', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Glúteos 4 Apoios', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Glúteos Coice na Polia', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Leg Press 45', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Leg Press 90', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Leg Press Horizontal', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Levantamento Terra', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Levantamento Terra Sumô', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Mesa Flexora', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Panturrilha Hack', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Panturrilha no Leg Press', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Panturrilha no Smith', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Panturrilha Sentado', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Passada', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Pistol', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Stiff', 'INFERIORES', 'MUSCULACAO', true, NOW()),
('Subida no Caixote', 'INFERIORES', 'MUSCULACAO', true, NOW()),

-- Aeróbio
('Air Bike', 'AEROBIO', 'AEROBICO', true, NOW()),
('Bicicleta', 'AEROBIO', 'AEROBICO', true, NOW()),
('Elíptico', 'AEROBIO', 'AEROBICO', true, NOW()),
('Escada Máquina', 'AEROBIO', 'AEROBICO', true, NOW()),
('Esteira', 'AEROBIO', 'AEROBICO', true, NOW()),
('Polichinelo', 'AEROBIO', 'AEROBICO', true, NOW()),
('Pular Corda', 'AEROBIO', 'AEROBICO', true, NOW()),
('Remo', 'AEROBIO', 'AEROBICO', true, NOW()),

-- Alongamento
('Alongamento de Abdômen', 'ALONGAMENTO', 'ALONGAMENTO', true, NOW()),
('Alongamento de Adutores', 'ALONGAMENTO', 'ALONGAMENTO', true, NOW()),
('Alongamento de Antebraço', 'ALONGAMENTO', 'ALONGAMENTO', true, NOW()),
('Alongamento de Coluna', 'ALONGAMENTO', 'ALONGAMENTO', true, NOW()),
('Alongamento de Dorsal', 'ALONGAMENTO', 'ALONGAMENTO', true, NOW()),
('Alongamento de Glúteos', 'ALONGAMENTO', 'ALONGAMENTO', true, NOW()),
('Alongamento de Ombros', 'ALONGAMENTO', 'ALONGAMENTO', true, NOW()),
('Alongamento de Panturrilha', 'ALONGAMENTO', 'ALONGAMENTO', true, NOW()),
('Alongamento de Peitoral', 'ALONGAMENTO', 'ALONGAMENTO', true, NOW()),
('Alongamento de Pescoço', 'ALONGAMENTO', 'ALONGAMENTO', true, NOW()),
('Alongamento de Posteriores', 'ALONGAMENTO', 'ALONGAMENTO', true, NOW()),
('Alongamento de Punho', 'ALONGAMENTO', 'ALONGAMENTO', true, NOW()),
('Alongamento de Quadríceps', 'ALONGAMENTO', 'ALONGAMENTO', true, NOW()),
('Alongamento de Tríceps', 'ALONGAMENTO', 'ALONGAMENTO', true, NOW()),

-- Dorsal
('Banco Lombar', 'DORSAL', 'MUSCULACAO', true, NOW()),
('Barra Fixa', 'DORSAL', 'MUSCULACAO', true, NOW()),
('Barra Fixa Gráviton', 'DORSAL', 'MUSCULACAO', true, NOW()),
('Crucifixo Inverso', 'DORSAL', 'MUSCULACAO', true, NOW()),
('Face Pull', 'DORSAL', 'MUSCULACAO', true, NOW()),
('Pulldown', 'DORSAL', 'MUSCULACAO', true, NOW()),
('Pullover', 'DORSAL', 'MUSCULACAO', true, NOW()),
('Puxada Aberta', 'DORSAL', 'MUSCULACAO', true, NOW()),
('Puxada Fechada', 'DORSAL', 'MUSCULACAO', true, NOW()),
('Remada Baixa', 'DORSAL', 'MUSCULACAO', true, NOW()),
('Remada Cavalinho', 'DORSAL', 'MUSCULACAO', true, NOW()),
('Remada Curvada', 'DORSAL', 'MUSCULACAO', true, NOW()),
('Remada Máquina', 'DORSAL', 'MUSCULACAO', true, NOW()),
('Remada Unilateral (Serrote)', 'DORSAL', 'MUSCULACAO', true, NOW()),

-- Funcional
('Burpee', 'FUNCIONAL', 'FUNCIONAL', true, NOW()),
('Corda Naval', 'FUNCIONAL', 'FUNCIONAL', true, NOW()),
('Deslocamento Lateral', 'FUNCIONAL', 'FUNCIONAL', true, NOW()),
('Escada de Agilidade', 'FUNCIONAL', 'FUNCIONAL', true, NOW()),
('Skipping', 'FUNCIONAL', 'FUNCIONAL', true, NOW()),
('Swing Kettlebell', 'FUNCIONAL', 'FUNCIONAL', true, NOW()),

-- Ombro
('Desenvolvimento Arnold', 'OMBRO', 'MUSCULACAO', true, NOW()),
('Desenvolvimento com Barra', 'OMBRO', 'MUSCULACAO', true, NOW()),
('Desenvolvimento com Halteres', 'OMBRO', 'MUSCULACAO', true, NOW()),
('Desenvolvimento Máquina', 'OMBRO', 'MUSCULACAO', true, NOW()),
('Elevação Frontal', 'OMBRO', 'MUSCULACAO', true, NOW()),
('Elevação Lateral', 'OMBRO', 'MUSCULACAO', true, NOW()),
('Encolhimento de Ombros', 'OMBRO', 'MUSCULACAO', true, NOW()),
('Remada Alta', 'OMBRO', 'MUSCULACAO', true, NOW()),

-- Peitoral
('Crucifixo', 'PEITORAL', 'MUSCULACAO', true, NOW()),
('Crucifixo Inclinado', 'PEITORAL', 'MUSCULACAO', true, NOW()),
('Flexão de Braços', 'PEITORAL', 'MUSCULACAO', true, NOW()),
('Manguito Rotador Externo', 'PEITORAL', 'MUSCULACAO', true, NOW()),
('Manguito Rotador Interno', 'PEITORAL', 'MUSCULACAO', true, NOW()),
('Peck Deck', 'PEITORAL', 'MUSCULACAO', true, NOW()),
('Supino Declinado', 'PEITORAL', 'MUSCULACAO', true, NOW()),
('Supino Inclinado', 'PEITORAL', 'MUSCULACAO', true, NOW()),
('Supino Máquina', 'PEITORAL', 'MUSCULACAO', true, NOW()),
('Supino Reto', 'PEITORAL', 'MUSCULACAO', true, NOW()),

-- Bíceps
('Rosca Alternada', 'BICEPS', 'MUSCULACAO', true, NOW()),
('Rosca Concentrada', 'BICEPS', 'MUSCULACAO', true, NOW()),
('Rosca Direta', 'BICEPS', 'MUSCULACAO', true, NOW()),
('Rosca Martelo', 'BICEPS', 'MUSCULACAO', true, NOW()),
('Rosca Scott', 'BICEPS', 'MUSCULACAO', true, NOW()),

-- Antebraço
('Rosca de Punho', 'ANTEBRACO', 'MUSCULACAO', true, NOW()),
('Rosca Inversa', 'ANTEBRACO', 'MUSCULACAO', true, NOW()),

-- Tríceps
('Tríceps Banco', 'TRICEPS', 'MUSCULACAO', true, NOW()),
('Tríceps Coice', 'TRICEPS', 'MUSCULACAO', true, NOW()),
('Tríceps Francês', 'TRICEPS', 'MUSCULACAO', true, NOW()),
('Tríceps na Polia', 'TRICEPS', 'MUSCULACAO', true, NOW()),
('Tríceps Paralelas', 'TRICEPS', 'MUSCULACAO', true, NOW()),
('Tríceps Supinado', 'TRICEPS', 'MUSCULACAO', true, NOW()),
('Tríceps Testa', 'TRICEPS', 'MUSCULACAO', true, NOW()),

-- Mobilidade
('Mobilidade de Cervical', 'MOBILIDADE', 'MOBILIDADE', true, NOW()),
('Mobilidade de Corpo Inteiro', 'MOBILIDADE', 'MOBILIDADE', true, NOW()),
('Mobilidade de Escápula', 'MOBILIDADE', 'MOBILIDADE', true, NOW()),
('Mobilidade de Ombro', 'MOBILIDADE', 'MOBILIDADE', true, NOW()),
('Mobilidade de Quadril', 'MOBILIDADE', 'MOBILIDADE', true, NOW()),
('Mobilidade de Tornozelo', 'MOBILIDADE', 'MOBILIDADE', true, NOW()),
('Mobilidade Dorsal', 'MOBILIDADE', 'MOBILIDADE', true, NOW()),
('Mobilidade Torácica', 'MOBILIDADE', 'MOBILIDADE', true, NOW());